[package]
name = "fullscreenizer"
version = "1.0.0"
authors = ["Carter Persall <carterpersll@gmail.com>"]
edition = "2021"

[dependencies.winsafe]
version = "0.0.20"
features = [
    "gui",
    "comctl",
    "user",
    "kernel"
]

#[dependencies.tokio]
#version = "1.37.0"
#features = ["full"]

[dependencies.windows]
version = "0.58.0"
features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Controls",
    "Win32_Graphics_Dwm",
    "Win32_Graphics_Gdi",
    "Win32_System_LibraryLoader"
]

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = 3
strip = "symbols"

[profile.dev]
opt-level = 0
strip = "none"