[package]
name = "fullscreenizer"
version = "1.0.0"
authors = ["Carter Persall <carterpersll@gmail.com>"]
edition = "2024"

[dependencies.winsafe]
git = "https://github.com/rodrigocfd/winsafe.git"
rev = "ac42e6e8e6fe9061c7669c3350087248e97b8ecd"
features = [
    "advapi",
    "dwm",
    "gui",
    "comctl",
    "user",
    "uxtheme",
    "kernel"
]

[dependencies.windows]
version = "0.62.1"
features = [
    "Win32_Foundation",
    "Win32_Storage_Packaging_Appx",
    "Win32_Graphics_GdiPlus",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Shell",
]

[build-dependencies]
embed-resource = "3.0.11"

[profile.release]
lto = "fat"
codegen-units = 1
strip = "symbols"