[package]
name = "fullscreenizer"
version = "1.0.0"
authors = ["Carter Persall <carterpersll@gmail.com>"]
edition = "2024"

[dependencies.winsafe]
version = "0.0.25"
features = [
    "advapi",
    "gui",
    "comctl",
    "user",
    "uxtheme",
    "kernel"
]

[dependencies.windows]
version = "0.61.3"
features = [
    "Win32_Foundation",
    "Win32_Graphics_Dwm"
]

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = 3
strip = "symbols"

[profile.dev]
opt-level = 0
strip = "none"